# Generated by Django 5.1.15 on 2026-09-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SmsLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=35)),
                ("text", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "message_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                ("provider_response", models.JSONField(blank=True, null=True)),
                ("error", models.TextField(blank=True, default="")),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="DEPRECATED: mirrors status == SENT. Scheduled for removal in 3.0; read `status` instead.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log",
                "verbose_name_plural": "Logs",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["phone_number", "created_at"],
                        name="SMS_smslog_phone_n_eb22b6_idx",
                    )
                ],
            },
        ),
    ]
