# Generated by Django 4.0.6 on 2022-07-12 09:14

from typing import ClassVar

from django.db import migrations


class Migration(migrations.Migration):

    dependencies: ClassVar[list] = [
        ('SMS', '0001_initial'),
    ]

    operations: ClassVar[list] = [
        migrations.DeleteModel(
            name='SmsToken',
        ),
    ]
