# Generated by Django 4.0.6 on 2022-07-12 09:18

from typing import ClassVar

from django.db import migrations


class Migration(migrations.Migration):

    dependencies: ClassVar[list] = [
        ('SMS', '0002_delete_smstoken'),
    ]

    operations: ClassVar[list] = [
        migrations.RemoveField(
            model_name='smslog',
            name='code',
        ),
    ]
